# Generated by Django 4.1 on 2023-02-20 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Content title')),
                ('description', models.TextField(blank=True, max_length=256, verbose_name='Content description')),
                ('is_free', models.BooleanField(default=True)),
                ('user', models.ForeignKey(help_text='Seller user that published this content', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Kit title')),
                ('description', models.TextField(blank=True, max_length=256, verbose_name='Kit description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Seller user that published this kit', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('basecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contents.basecontent')),
            ],
            bases=('contents.basecontent',),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('basecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contents.basecontent')),
            ],
            bases=('contents.basecontent',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('basecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contents.basecontent')),
            ],
            bases=('contents.basecontent',),
        ),
        migrations.CreateModel(
            name='KitContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.kit')),
                ('document_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.document')),
                ('image_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.image')),
                ('video_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.video')),
            ],
        ),
    ]
