# Generated by Django 4.1 on 2023-02-20 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kitcontent",
            name="content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="kits_included", to="contents.content"
            ),
        ),
        migrations.AlterField(
            model_name="kitcontent",
            name="kit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="contents", to="contents.kit"
            ),
        ),
    ]
