[tool.black]
line-length = 120

[tool.isort]
profile = "black"
src_paths = ["isort", "test"]
known_django = ["django", "rest_framework"]
known_first_party = ["users", "contents"]
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
