name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    services:
      db:
        image: postgres:12.8
        env:
          POSTGRES_DB: eureka_core
          POSTGRES_USER: uoe
          POSTGRES_PASSWORD: uoe1234
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements-dev.txt
    - name: Run Tests
      run: |
        python manage.py test
